### ISSUE TITLE
Question: Toplevel optional commands?

### ISSUE THREAD

**Issue by leeola** [jessevdk/go-flags#138]
Based on a reply _(https://github.com/jessevdk/go-flags/issues/71#issuecomment-41650920)_ to another issue with a similar question, it appears that toplevel commands cannot be optional via struct fields.

With that said, is it possible at all? If so, how? _(Example much appreciated!)_

Thanks to any replies,

**Comment by jessevdk** [comment]
It's not possible using tags, since you wouldn't be able to specify them on the main struct. However, you can simply set [SubcommandsOptional](https://godoc.org/github.com/jessevdk/go-flags#Command.SubcommandsOptional) on the [Parser](https://godoc.org/github.com/jessevdk/go-flags#) instance that you create. For example, the equivalent of:

```go
args, err := flags.Parse(&opts)
```

would be:

```go
parser := flags.NewParser(&opts, flags.Default)
parser.SubcommandsOptional = true
args, err := parser.Parse()
```
