### ISSUE TITLE
Please consider SemVer 2.0.0 versioning

### ISSUE THREAD

**Issue by jechols** [jessevdk/go-flags#206]
e.g., instead of tagging "v1.1" (or in addition), tag "v1.1.0".  This enables `gb` (https://github.com/constabulary/gb/issues) to easily download your package as a tarball instead of cloning the git repository.

**Comment by zimmski** [comment]
@jessevdk: I am voting for this too. Afaik some users requested tags a long time ago and did tag 1.1 a while ago. If this makes the gb crowd happy, I see no reason not to do it. The semantic versioning rules http://semver.org/ are also pretty easy for go-flags since we do not do any API breaking changes.

**Comment by jessevdk** [comment]
I'm fine with it, I just don't care too much about it.

**Comment by jessevdk** [comment]
Added `v1.1.0` tag to `v1.1`, released new `v1.2.0` version.
