### ISSUE TITLE
[Problem] Command fail to parse when "default" field tag is added

### ISSUE THREAD

**Issue by FrankieYin** [jessevdk/go-flags#266]
Hi @jessevdk,

For my `app`, I have a command `cmd` and an optional boolean flag `--p`. When I label the flag with
```
optional:"yes" optional-value:"true" default:"true"
```
The command would not be parsed by go-flags, i.e. when I do `app cmd` a help message will be printed saying "Unknown command `cmd`". I think this is a bug. If not, could you tell me where went wrong and how should I use the `optional` and several other related field tags, as I couldn't find any example in the documents.

Kind regards,
Zhijun

**Comment by FrankieYin** [comment]
**Update:** changing the flag type from `bool` to `string` allowed the `cmd` command to be parsed normally; however to get my desired behaviour I had to remove `optional-value` tag as well.

I don't think the docs made this clear: both the fact that `default` wouldn't work on `bool` type and the fact that `optional-value` does not work with `default` tag. It would be really helpful if you could add that to the current doc? @jessevdk

**Comment by jessevdk** [comment]
Setting a default value for a bool flag will lead to an error (you can print the error returned from the parser). We did this because boolean flags can only be turned on by specifying them, and so setting a default like `false` isn't possible. Therefore, to avoid confusion, all default values are an error for boolean flags.

Similarly, boolean flags cannot have any arguments, although we currently don't error if you specify that it has an optional value.
