### ISSUE TITLE
Project status - considered done? not enought time? other priorities?

### ISSUE THREAD

**Issue by jrossi** [jessevdk/go-flags#317]
This project is has not been updated sense "_Commits on Dec 21, 2018_" and from godocs.org 

> Package flags imports 17 packages (graph) and is imported by 1535 packages. Updated 4 days ago. Refresh now. Tools for package owners. 

I am a happy user of this package/library and I am not alone, but their seams to be other priorities for the maintainer.  Is this something the community can help with?  

@jessevdk let us know if we can do anything.

**Comment by zimmski** [comment]
I wrote some of go-flags code and I still have write access to it. I would love to work on go-flags again but since I founded a new company (Symflower) I am currently completely overbooked with work. This saddens me especially since I have a lot of open source projects that suffer for the same reason, and I feel guilty for not doing something almost every day. I really love doing open source. I am sure that this will get better for me (looking forward to "open source Friday" in the future of our company) but until things are stable I have to priorities the work that allows us to be successful. Sadly, the priority is not open source at the moment and therefore not go-flags. I guess Jesse has the same problem and feeling with go-flags. I think an additional maintainer is a good idea if @jessevdk is up for it. Although, I am not sure how we would search for one.

Also, about the "considered done". I still use go-flags for every binary because defining the "structs" feels "right" for me. However, I would love to see two things: a.) a go-flags that can be configured and is by default really really small in size. E.g. for a lot of binaries we do not really need "INI" files but we would need JSON. Others might need YAML or a database configuration of some kind. b.) APIs to manage options/groups/.../everything and then generate source code.

**Comment by jrossi** [comment]
@zimmski I completely understand about time available issue, and I am in the same place with no time. 

I do hope someone has the time to continue with the project as I am still using it and have left 100's of cli tools in my wake over the years that all use go-flags.  

@zimmski  and @jessevdk thank you for go-flags, and everyone that contributed to the go-flags: https://github.com/jessevdk/go-flags/graphs/contributors

**Comment by jessevdk** [comment]
Contributions are welcome. I very occasionally still try to process obvious bugs or enhancements but I consider the package quite feature complete in general and it's definitely in maintenance mode.
